exp_name: '4encoder_8liftlayer_res224'
exp_group: 'leap-objaverseXL'
output_dir: './output/'
log_dir: './log'
workers: 4
print_freq: 100
vis_freq: 500
eval_vis_freq: 10
seed: 42

# dataset config
dataset:
  name: 'objaverse'
  category: 'general'
  task: 'singlesequence'
  img_size: 518
  img_size_render: 259
  num_frame: 4
  mask_images: True
  augmentation: False
  train_all_frame: False

# network config
model:
  norm_first: False
  # backbone
  backbone_name: 'dinov2'
  backbone_type: 'vitb14'
  backbone_fix: False
  backbone_out_dim: 768 ###<=======================hugging-face hidden-size
  module_camera_feature: True ####<=====================magic thing 
  backbone_path_size: 14  ####<=====================magic thing 
  # pe transformer
  use_neck: False
  neck_scale: 'constant_1' #'channel' #'constant_1'
  neck_layers: 2
  pe_with_spatial_pe: False
  # single_stream_transformer
  lifting_use_conv3d: False
  hidden_size: 1024
  layers: 24
  heads: 16
  latent_res: 32
  # rendering
  volume_res: 96
  render_feat_dim: 3
  render_feat_raw: False
  # others
  rot_representation: 'quat'
  use_flash_attn: False

# render config
render:
  n_pts_per_ray: 64
  volume_size: 1.4
  min_depth: 1.0
  max_depth: 2.7
  camera_z: 1.85 # camera pose T_z, range [1.5, 2.2]
  k_size: 5

# loss config
loss:
  weight_render_rgb: 1.0
  weight_render_mask: 3.0
  weight_perceptual: 0.2
  iter_perceptual: 10000
  weight_feat_render: 5.0

# training config
train:
  resume: False
  lr: 0.0001
  lr_embeddings: 0.0001
  lr_backbone: 0.000005  # 0.00002
  weight_decay: 0.0005
  schedular_warmup_iter: 500
  total_iteration: 200000
  batch_size: 2
  accumulation_step: 2
  normalize_img: True
  grad_max: 5.0
  use_amp: False
  use_rand_view: False
  min_rand_view: 3
  use_uncanonicalized_pose: False
  #pretrain_path: 'output/kubric/train_224/base_res224_lr2x_percploss-0.1_res32_encoder-nonfix-1e-5_no-neck_no-feat-render-loss/cpt_best_psnr_27.224168484870876.pth.tar'
  pretrain_path: ''

# test config
test:
  batch_size: 1
  compute_metric: True